name: Run Postman Collection (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  postman-tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '17'

      - name: Install Newman v3 and HTML Extra Reporter
        run: |
          npm install -g newman@3
          npm install -g newman-reporter-htmlextra

      - name: Run Postman collection
        run: |
          mkdir reports
          newman run Collection_Client.postman_collection.json -r htmlextra --reporter-htmlextra-export reports/postman-report.html

      - name: Publish Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: reports/postman-report.html
